<?php
require_once('OoyalaApi.php');

/**
 * Implements hook_help.
 * 
 * Displays help and module information
 *
 */
function ooyala_pingback_help($path, $arg) {
}

/**
 * Implements hook_menu.
 */
function ooyala_pingback_menu() {
  $items = array();

  $items['ooyala/status'] = array('title' => 'Ooyala Processing Callback Handler',
		       'page callback' => 'ooyala_pingback_action',
		       'page arguments' => array(),
		       'delivery callback' => 'ooyala_pingback_delivery',
		       'access callback' => true,
		       'type' => MENU_CALLBACK,
		       );
  return $items;
}

/**
 * Implements the callback action.
 *
 * This module is an Ooyala API processing ping handler.
 * See http://support.ooyala.com/developers/documentation/concepts/api_pingurl.html).

 * The function does the following:
 * - retrieves the metadata associated with the given embedcode;
 * - checks whether there is a trailer metadata field, which is expected to have
 *   an external id as it's value; 
 * - looks up the embedcode associated with the trailer external id; and
 * - creates / updates the 'trailer_embed' metadata field on the processed asset.
 *
 */
function ooyala_pingback_action() {
  $result = array();
  $ooyala_api = new OoyalaApi('4zYTAxOo2vwj-0QgUN3pYHGKUagI.qxKT_','7iUsHFZBDHy4UkB8B0UwvRGDpHvc_fpAH4aXLQDh');
  
  if (isset($_GET['embedCode'])) {
    $embed = $_GET['embedCode'];
    $metadata_path = '/v2/assets/' . $embed . '/metadata';
    try {
      $metadata = $ooyala_api->get($metadata_path);
      if(property_exists($metadata, 'trailer')) { 
	$trailer_asset = $ooyala_api->get('/v2/assets/' . $metadata->trailer);
	$asset_meta = array('trailer_embed' => $trailer_asset->embed_code);
	$ooyala_api->patch($metadata_path, $asset_meta);
	$result['message'] = 'Patched trailer metadata for ' . $embed . ':' . $metadata->trailer . ' -> ' . $trailer_asset->embed_code; 
      } else {
	$result['message'] = 'Content' . $embed . ' does not have a \'trailer\' metadata field';
	watchdog('ooyala_pingback',$result);
      }
    } catch (OoyalaRequestErrorException $e) {
      $result['message'] = $e->getMessage();
      watchdog('ooyala_pingback',$result);
    }
  } else {
    $result['message'] = 'Did not received parameter \'embedCode\'';
    $result['error'] = true;
    watchdog('ooyala_pingback',$result,null,WATCHDOG_ERROR);
  }
  return $result;
}

/** 
 * There is not content to deliver back as a result of making this call.
 */
function ooyala_pingback_delivery($result) {
  drupal_add_http_header("Content-Type","text/plain; charset=\"utf-8\"");
  print $result['message'];
}
